### ISSUE TITLE
Is this the rt-linux patch?

### ISSUE THREAD

**Issue by DerrickLau** [clrkwllms/rt-linux#1]
Is this the real-time LINUX kernel patch that should be applied on top of a LINUX OS kernel in order to get real-time features?  Or is it a full real-time LINUX OS that I can just install and use immediately?  Also, does this flavor of RT-Linux run regular Linux within one of the real-time tasks?  And you write your own real-time tasks to execute in the others?

**Comment by clrkwllms** [comment]
Oh wow, that's ancient (as in I really need to delete that thing).

That's an old Linux kernel tree with the PREEMPT_RT patchset (i.e. the RT
Linux patch)  applied.

If you want a Linux kernel that is setup for consistent response time for
events, then get the code from either the stable repo or the devel repo up
on kernel.org:

https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git/
https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git/

**Comment by DerrickLau** [comment]
Thanks for the quick response.  Greatly appreciated!

**Comment by DerrickLau** [comment]
And those two GitHub links are full Linux installs (ie I can install them on an old x64 PC and it will boot up to the Linux command prompt?  And those two GitHub links comply with all the hard real-time constraints?

**Comment by clrkwllms** [comment]
Neither of those are github links, they're links to kernel.org where we
keep the upstream source for the RT kernel. You'll need to pull that source
code and compile it before you can boot it.

As far as meeting hard real-time constraints, that depends entirely on what
your timing deadlines are. If you're trying to consistently service events
in the single-digit microsecond timeframe then you're probably better off
using a dedicated RTOS rather than using Linux. If you're just trying to
reduce audio/video jitter then it will help. Fair warning, to get the best
performance from an RT Linux kernel, you'll need to do lots of tuning.
